### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Zoooe-Brooo** [Zoooe-Brooo/prework-study-guide#1]
# HTML

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information 

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my own browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by asad7coder** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prework Study Guide</title>
    <style>
        /* Basic styling for the boxes */
        .box {
            border: 1px solid #ccc;
            padding: 20px;
            margin: 20px;
            width: 200px;
            float: left;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="box">
        <h2>HTML</h2>
        <p>HTML notes go here...</p>
    </div>
    <div class="box">
        <h2>CSS</h2>
        <p>CSS notes go here...</p>
    </div>
    <div class="box">
        <h2>Git</h2>
        <p>Git notes go here...</p>
    </div>
    <div class="box">
        <h2>JavaScript</h2>
        <p>JavaScript notes go here...</p>
    </div>
</body>
</html>
